document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <style>");
document.writeln("        .footer{");
document.writeln("            height: 50px;");
document.writeln("            width: 100%;");
document.writeln("            background-color: black;");
document.writeln("            position: absolute;");
document.writeln("            bottom: 0;");
document.writeln("        } ");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\'footer\'>");
document.writeln("        <div class=\'footer_w wrapper\' style=\'text-align:center; line-height: 50px;\'>");
document.writeln("            <span style=\'color: #fff; \'>桂林电子科技大学 | 商学院 | 信息管理与信息系统 | 少儿编程平台(2020)</span>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");