document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <script src=\'../resource/js/jquery.min.js\'></script>");
document.writeln("    <style>");
document.writeln("        *{");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;");
document.writeln("        }");
document.writeln("        body{");
document.writeln("            font: 14px/1.5 Helvetica Neue,Helvetica,Arial,Microsoft Yahei,Hiragino Sans GB,Heiti SC,WenQuanYi Micro Hei,sans-serif;");
document.writeln("            position : relative;");
document.writeln("            padding-bottom: 230px;");
document.writeln("        }");
document.writeln("        .topbar{");
document.writeln("            height: 40px;");
document.writeln("            background-color: #333;");
document.writeln("            font-size: 14px;");
document.writeln("            line-height: 40px;");
document.writeln("        }");
document.writeln("        .wrapper{");
document.writeln("            width: 1200px;");
document.writeln("            margin: 0 auto;");
document.writeln("        }");
document.writeln("        .topbar-list{");
document.writeln("            float: left;");
document.writeln("        }");
document.writeln("        .topbar a{");
document.writeln("            color: #fff;");
document.writeln("            text-decoration: none;");
document.writeln("        }");
document.writeln("        .topbar a:hover{");
document.writeln("            color: #ddd;");
document.writeln("        }");
document.writeln("        .topbar span{");
document.writeln("            color: #fff;");
document.writeln("            margin: 0 2px;");
document.writeln("        }");
document.writeln("        .topbar-info{");
document.writeln("            float: right;");
document.writeln("        }");
document.writeln("        .nav{");
document.writeln("            list-style-type: none;");
document.writeln("        }");
document.writeln("        .nav>li{");
document.writeln("            float: left;");
document.writeln("        }");
document.writeln("        .nav>li>ul>li{");
document.writeln("            display: block;");
document.writeln("            position: relative;");
document.writeln("            right: 10px;");
document.writeln("            border-top: 1px solid black;");
document.writeln("            text-align: center;");
document.writeln("            background-color: #333;    ");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("    <script>");
document.writeln("        $(function(){");
document.writeln("            $(\'.scrDown ul\').hide();");
document.writeln("            $(\'.scrDown\').on({");
document.writeln("                mouseover:function(){$(this).children(\'ul\').show();},");
document.writeln("                mouseout:function(){$(this).children(\'ul\').hide();}");
document.writeln("            });");
document.writeln("        })");
document.writeln("    </script>");
document.writeln("</head>");
document.writeln("<body\'>");
document.writeln("    <div class=\'topbar\'>");
document.writeln("        <div class=\'wrapper\'>");
document.writeln("            <div class=\'topbar-list\'>");
document.writeln("                <ul class=\'nav\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'index.html\'>首页</a>");
document.writeln("                        <span>|</span>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'scrDown\'>");
document.writeln("                        <a href=\'\'>Scratch教程</a>");
document.writeln("                        <span>|</span>");
document.writeln("                        <ul>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'graphic&text.html\'>图文教程</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'videoteach.html\'>视频教程</a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'scrDown\'>");
document.writeln("                        <a href=\'#\'>Scratch社区</a>");
document.writeln("                        <span>|</span>");
document.writeln("                        <ul>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'exchange.html\'>编程交流</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'workshow.html\'>作品分享</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'edu.html\'>教育咨询</a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'workshow.html\'>素材库</a>");
document.writeln("                        <span>|</span>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'user.html\'>个人中心</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'topbar-info\'>");
document.writeln("                <a href=\'login.html\'>登录</a>");
document.writeln("                <span>|</span>");
document.writeln("                <a href=\'register.html\'>注册</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");